import {AfterViewInit, Component, Input, OnInit} from "@angular/core";
import {MolView, ConstructorParams, ContextInfo, MolViewRenderMode, MolViewSelectionMode} from "wglmolview";
import {MatCardModule} from '@angular/material/card';
import {AtomInfoComponent} from "../atom_info/atom.info.component";

@Component({
  selector: 'molview',
  standalone: true,
  imports: [MatCardModule, AtomInfoComponent],
  templateUrl: './molview.component.html',
  styleUrl: './molview.component.css'
})
export class MolViewComponent implements AfterViewInit {

  private readonly pdb = `HEADER    AMINO ACID
COMPND    ALANINE (ALA or A)
AUTHOR    GENERATED BY GLACTONE
ATOM      1  N   ALA  0001      -1.053   1.300   0.614
ATOM      2  CA  ALA  0001      -0.304   0.032   0.746
ATOM      3  C   ALA  0001       0.770  -0.014  -0.311
ATOM      4  O   ALA  0001       1.952  -0.167  -0.047
ATOM      5  H   ALA  0001      -1.805   1.385   1.386
ATOM      6  O   ALA  0001       0.354   0.125  -1.567
ATOM      7  H   ALA  0001      -1.522   1.368  -0.358
ATOM      8  H   ALA  0001       0.176   0.013   1.740
ATOM      9  C   ALA  0001      -1.237  -1.200   0.610
ATOM     10  H   ALA  0001      -2.007  -1.183   1.397
ATOM     11  H   ALA  0001      -0.655  -2.129   0.709
ATOM     12  H   ALA  0001      -1.737  -1.199  -0.371
ATOM     13  H   ALA  0001       1.100   0.082  -2.154
CONECT    1    2    5    7
CONECT    2    1    3    8    9
CONECT    3    2    4    4    6
CONECT    4    3    3
CONECT    5    1
CONECT    6    3   13
CONECT    7    1
CONECT    8    2
CONECT    9    2   10   11   12
CONECT   10    9
CONECT   11    9
CONECT   12    9
CONECT   13    6
END
`;

  private params: ConstructorParams =
    {domElement: "viewport", pdbData: this.pdb, onInfoUpdated: (info: ContextInfo) => {
      this.info = info.message||"";
      const id = parseInt(info?.atoms?.[0]?.id?.replace("atom", ""));
      this.selectedAtomId = !isNaN(id) ? id : 0;
      this.data = this.pdb;
    }};

  private mv?:MolView;
  public info: string = "";

  public selectedAtomId: number = 0;
  public data: string = "";

  constructor() {
  }

  ngAfterViewInit(): void {
    this.mv = new MolView(this.params);
    }

  @Input() set renderMode(mode: MolViewRenderMode) {
      this.mv?.setRenderMode(mode);
  }

  @Input() set selectionMode(mode: MolViewSelectionMode) {
      this.mv?.setSelectionMode(mode);
  }

  @Input() set pdbData(data: string) {
      this.mv?.setPDBData(data);
      this.data = data;
  }
}
